software:
  charms:
    aodh-k8s:
      channel: 2023.2/edge
    barbican-k8s:
      channel: 2023.2/edge
    ceilometer-k8s:
      channel: 2023.2/edge
    cinder-ceph-k8s:
      channel: 2023.2/edge
    cinder-k8s:
      channel: 2023.2/edge
    designate-bind-k8s:
      channel: 9/edge
    designate-k8s:
      channel: 2023.2/edge
    glance-k8s:
      channel: 2023.2/edge
    gnocchi-k8s:
      channel: 2023.2/edge
    heat-k8s:
      channel: 2023.2/edge
    horizon-k8s:
      channel: 2023.2/edge
    keystone-k8s:
      channel: 2023.2/edge
    keystone-ldap-k8s:
      channel: 2023.2/edge
    magnum-k8s:
      channel: 2023.2/edge
    neutron-k8s:
      channel: 2023.2/edge
    nova-k8s:
      channel: 2023.2/edge
    octavia-k8s:
      channel: 2023.2/edge
    openstack-exporter-k8s:
      channel: 2023.2/edge
    openstack-hypervisor:
      channel: 2023.2/edge
      config:
        snap-channel: 2023.2/edge
    ovn-central-k8s:
      channel: 23.09/edge
    ovn-relay-k8s:
      channel: 23.09/edge
    placement-k8s:
      channel: 2023.2/edge
    sunbeam-clusterd:
      channel: 2023.2/edge
      config:
        snap-channel: 2023.2/edge
    sunbeam-machine:
      channel: 2023.2/edge
    tempest-k8s:
      channel: 2023.2/edge
    microceph:
      channel: reef/edge
